"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PageHeader = exports.PageContainer = exports.GlassContainer = exports.HighlightText = exports.GlowText = void 0;
var styles_1 = require("@mui/material/styles");
var Typography_1 = __importDefault(require("@mui/material/Typography"));
var Box_1 = __importDefault(require("@mui/material/Box"));
var Stack_1 = __importDefault(require("@mui/material/Stack"));
exports.GlowText = (0, styles_1.styled)(Typography_1.default)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    text-shadow: 0 0 20px rgba(255, 255, 255, 0.1);\n    letter-spacing: -0.02em;\n"], ["\n    text-shadow: 0 0 20px rgba(255, 255, 255, 0.1);\n    letter-spacing: -0.02em;\n"])));
exports.HighlightText = (0, styles_1.styled)(Typography_1.default)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    background: linear-gradient(90deg, #FFFFFF 0%, rgba(255, 255, 255, 0.8) 100%);\n    -webkit-background-clip: text;\n    -webkit-text-fill-color: transparent;\n    background-clip: text;\n    text-fill-color: transparent;\n"], ["\n    background: linear-gradient(90deg, #FFFFFF 0%, rgba(255, 255, 255, 0.8) 100%);\n    -webkit-background-clip: text;\n    -webkit-text-fill-color: transparent;\n    background-clip: text;\n    text-fill-color: transparent;\n"])));
exports.GlassContainer = (0, styles_1.styled)(Box_1.default)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    background: rgba(255, 255, 255, 0.03);\n    backdrop-filter: blur(10px);\n    border-radius: 24px;\n    padding: 24px;\n    border: 1px solid rgba(255, 255, 255, 0.1);\n"], ["\n    background: rgba(255, 255, 255, 0.03);\n    backdrop-filter: blur(10px);\n    border-radius: 24px;\n    padding: 24px;\n    border: 1px solid rgba(255, 255, 255, 0.1);\n"])));
exports.PageContainer = (0, styles_1.styled)(Stack_1.default)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    position: relative;\n    &::before {\n        content: '';\n        position: absolute;\n        top: 0;\n        left: 0;\n        right: 0;\n        height: 200px;\n        background: linear-gradient(180deg, rgba(10, 3, 30, 0.8) 0%, rgba(10, 3, 30, 0) 100%);\n        pointer-events: none;\n        z-index: -1;\n    }\n"], ["\n    position: relative;\n    &::before {\n        content: '';\n        position: absolute;\n        top: 0;\n        left: 0;\n        right: 0;\n        height: 200px;\n        background: linear-gradient(180deg, rgba(10, 3, 30, 0.8) 0%, rgba(10, 3, 30, 0) 100%);\n        pointer-events: none;\n        z-index: -1;\n    }\n"])));
exports.PageHeader = (0, styles_1.styled)(Stack_1.default)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    margin-bottom: 4rem;\n    position: relative;\n    &::after {\n        content: '';\n        position: absolute;\n        bottom: -2rem;\n        left: 50%;\n        transform: translateX(-50%);\n        width: 100px;\n        height: 1px;\n        background: linear-gradient(90deg, \n            rgba(255, 255, 255, 0) 0%, \n            rgba(255, 255, 255, 0.2) 50%, \n            rgba(255, 255, 255, 0) 100%);\n    }\n"], ["\n    margin-bottom: 4rem;\n    position: relative;\n    &::after {\n        content: '';\n        position: absolute;\n        bottom: -2rem;\n        left: 50%;\n        transform: translateX(-50%);\n        width: 100px;\n        height: 1px;\n        background: linear-gradient(90deg, \n            rgba(255, 255, 255, 0) 0%, \n            rgba(255, 255, 255, 0.2) 50%, \n            rgba(255, 255, 255, 0) 100%);\n    }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
